[tools]
  node = "latest"
  pnpm = "latest"

[tasks.build]
  run = "pnpm install && pnpm run build"

[tasks.test]
  run = "pnpm run test"

[tasks.check]
  run = "pnpm run check"

[tasks.check-unsafe]
  run = "pnpm run check:unsafe"
