[tools]
  gleam = "latest"
  node  = "latest"
  pnpm  = "latest"

[tasks.install]
  run = "pnpm install"

[tasks.build]
  run = "pnpm install && pnpm run build"

[tasks.test]
  run = "pnpm run test"

[tasks.check]
  run = "pnpm run check"
